export const ERROR_CODES = {
  // Auth ile ilgili hatalar
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_SESSION: 'INVALID_SESSION',
  CLIENT_INFO_MISMATCH: 'CLIENT_INFO_MISMATCH',
  TEST_CLIENT_NOT_ALLOWED: 'TEST_CLIENT_NOT_ALLOWED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Sistem durumu
  MAINTENANCE: 'MAINTENANCE',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES; 